# Generated by Django 4.2.19 on 2025-04-28 21:19

import AudioXApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('audiobook_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('narrator', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_url', models.URLField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'AUDIOBOOKS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('bio', models.TextField(default='')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('coins', models.IntegerField(default=0)),
                ('subscription_type', models.CharField(choices=[('FR', 'Free'), ('PR', 'Premium')], default='FR', max_length=2)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA Enabled')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='audiox_users', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='audiox_users_permissions', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='creator_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_audiobooks', models.PositiveIntegerField(default=0)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cnic_front', models.ImageField(help_text='Clear image of the front of the CNIC.', null=True, upload_to=AudioXApp.models.creator_cnic_path)),
                ('cnic_back', models.ImageField(help_text='Clear image of the back of the CNIC.', null=True, upload_to=AudioXApp.models.creator_cnic_path)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Admin verification status for the creator.', max_length=10)),
                ('terms_accepted_at', models.DateTimeField(blank=True, help_text='Timestamp when the creator accepted terms during registration.', null=True)),
            ],
            options={
                'db_table': 'CREATORS',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('monthly', 'Monthly Premium'), ('annual', 'Annual Premium'), ('free', 'Free Tier')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('pending', 'Pending Payment')], default='active', max_length=10)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'SUBSCRIPTIONS',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('reward', 'Reward'), ('spent', 'Spent'), ('refund', 'Refund'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received')], max_length=15)),
                ('amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('pack_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'COIN_TRANSACTIONS',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_order', models.PositiveIntegerField()),
                ('chapter_time', models.PositiveIntegerField(default=0, help_text='Start time in seconds')),
                ('chapter_duration', models.PositiveIntegerField(default=0, help_text='Duration in seconds')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chapters/')),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='AudioXApp.audiobook')),
            ],
            options={
                'db_table': 'CHAPTERS',
                'ordering': ['chapter_order'],
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('roles', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this admin belongs to. An admin will get all permissions granted to each of their groups.', related_name='audiox_admins', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this admin.', related_name='audiox_admins_permissions', to='auth.permission')),
            ],
            options={
                'db_table': 'ADMINS',
            },
        ),
        migrations.AddField(
            model_name='audiobook',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks', to='AudioXApp.creator'),
        ),
    ]
