# Generated by Django 4.2.19 on 2025-07-25 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='When the message was last edited.', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='File attachment for the message.', null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether this message has been edited.'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, help_text='Users mentioned in this message.', related_name='mentioned_in_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Message this is a reply to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='AudioXApp.chatmessage'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('audiobook_recommendation', 'Audiobook Recommendation'), ('user_joined', 'User Joined Notification'), ('user_left', 'User Left Notification'), ('room_created', 'Room Created Notification'), ('room_renamed', 'Room Renamed Notification'), ('room_closed', 'Room Closed Notification'), ('file_attachment', 'File Attachment')], default='text', max_length=30),
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs Up'), ('❤️', 'Heart'), ('😂', 'Laughing'), ('😮', 'Surprised'), ('😢', 'Sad'), ('😡', 'Angry'), ('🎉', 'Party'), ('📚', 'Book'), ('💡', 'Light Bulb'), ('🔥', 'Fire')], help_text='Emoji reaction.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='AudioXApp.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Reaction',
                'verbose_name_plural': 'Message Reactions',
                'db_table': 'MESSAGE_REACTIONS',
                'ordering': ['created_at'],
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
    ]
