# Generated by Django 4.2.19 on 2025-05-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description for the chatroom.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chatrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'CHAT_ROOMS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('audiobook_recommendation', 'Audiobook Recommendation'), ('user_joined', 'User Joined'), ('user_left', 'User Left'), ('user_kicked', 'User Kicked'), ('user_added', 'User Added'), ('role_changed', 'Role Changed'), ('room_created', 'Room Created')], default='text', max_length=30)),
                ('content', models.TextField(help_text='Text content of the message.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommended_audiobook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_recommendations', to='AudioXApp.audiobook')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='AudioXApp.chatroom')),
                ('user', models.ForeignKey(blank=True, help_text='User who sent the message. Null if system message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'CHAT_MESSAGES',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('owner', 'Owner')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to='AudioXApp.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Room Member',
                'verbose_name_plural': 'Chat Room Members',
                'db_table': 'CHAT_ROOM_MEMBERS',
                'ordering': ['room', 'joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoomInvitation',
            fields=[
                ('invitation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invited_email', models.EmailField(help_text='Email of the user to be invited.', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_invitations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='AudioXApp.chatroom')),
            ],
            options={
                'verbose_name': 'Chat Room Invitation',
                'verbose_name_plural': 'Chat Room Invitations',
                'db_table': 'CHAT_ROOM_INVITATIONS',
                'ordering': ['-created_at'],
                'unique_together': {('room', 'invited_email')},
            },
        ),
    ]
