# Generated by Django 4.2.19 on 2025-04-28 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AudioXApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='creator_name',
            field=models.CharField(help_text='The public display name for the creator (e.g., studio name or full name).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='creator_unique_name',
            field=models.CharField(help_text='The unique handle for the creator (@yourname). Letters, numbers, and underscores only.', max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_creator_unique_name', message='Unique name can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='admin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Groups.', related_name='audiox_admins', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions.', related_name='audiox_admins_permissions', to='auth.permission'),
        ),
    ]
