# Generated by Django 4.2.19 on 2025-05-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='is_creator_book',
            field=models.BooleanField(default=True, help_text='True if uploaded by a platform creator, False if a placeholder for an external book.'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='source',
            field=models.CharField(choices=[('creator', 'Creator Upload'), ('librivox', 'LibriVox'), ('archive', 'Archive.org')], db_index=True, default='creator', help_text='Source of the audiobook (Creator, LibriVox, Archive.org)', max_length=10),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='audiobook_covers/'),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiobooks', to='AudioXApp.creator'),
        ),
    ]
