# Generated by Django 4.2.19 on 2025-05-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='old_request_id',
            field=models.CharField(blank=True, help_text='Legacy request ID, if applicable.', max_length=255, null=True),
        ),
    ]
