# Generated by Django 4.2.19 on 2025-05-23 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0002_withdrawalrequest_old_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned_by_admin',
            field=models.BooleanField(default=False, help_text='Set to true if the user is banned from the entire platform by an admin.'),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_ban_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin if the user is banned from the platform.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_banned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user was banned from the platform.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='platform_banned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who banned this user from the platform.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_banned_users', to='AudioXApp.admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'),
        ),
    ]
