# Generated by Django 4.2.19 on 2025-05-27 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0002_chatroom_chatmessage_chatroommember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(help_text='Content of the message. For recommendations, this might be an optional comment.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('audiobook_recommendation', 'Audiobook Recommendation'), ('user_joined', 'User Joined Notification'), ('user_left', 'User Left Notification')], default='text', max_length=30),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='recommended_audiobook',
            field=models.ForeignKey(blank=True, help_text='Link to an audiobook if this message is a recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_recommendations', to='AudioXApp.audiobook'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who sent the message. Null for system messages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the chat room.', null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(help_text='Name of the chat room.', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who created and owns the room.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chatrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroommember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin')], default='member', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='chatroominvitation',
            unique_together={('room', 'invited_email', 'status')},
        ),
    ]
