# Generated by Django 4.2.19 on 2025-05-25 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0002_audiobook_is_creator_book_audiobook_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_seconds', models.PositiveIntegerField(default=0, help_text='Timestamp in seconds where the user left off within the audiobook or current chapter.')),
                ('last_listened_at', models.DateTimeField(auto_now=True)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to='AudioXApp.audiobook')),
                ('current_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listening_markers', to='AudioXApp.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listening History',
                'verbose_name_plural': 'Listening Histories',
                'db_table': 'LISTENING_HISTORY',
                'ordering': ['-last_listened_at'],
                'unique_together': {('user', 'audiobook')},
            },
        ),
    ]
