# Generated by Django 4.2.19 on 2025-04-29 10:46

import AudioXApp.models
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0003_alter_admin_options_remove_admin_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiobook',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['audiobook', 'chapter_order']},
        ),
        migrations.AddField(
            model_name='audiobook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='audiobook_covers/'),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='admin',
            name='roles',
            field=models.CharField(help_text='Comma-separated list of roles', max_length=255),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('processing', 'Processing'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('reward', 'Reward'), ('spent', 'Spent'), ('refund', 'Refund'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('withdrawal', 'Withdrawal'), ('withdrawal_fee', 'Withdrawal Fee')], max_length=15),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cnic_back',
            field=models.ImageField(help_text='Back of CNIC', null=True, upload_to=AudioXApp.models.creator_cnic_path),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cnic_front',
            field=models.ImageField(help_text='Front of CNIC', null=True, upload_to=AudioXApp.models.creator_cnic_path),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_name',
            field=models.CharField(help_text='Public display name', max_length=100),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_unique_name',
            field=models.CharField(help_text='Unique handle (@yourname)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_creator_unique_name', message='Unique name can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='creator',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='total_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='creator',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('audiobook', 'chapter_order')},
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount requested for withdrawal in PKR', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('processed_date', models.DateTimeField(blank=True, help_text='Timestamp when payment was processed/completed', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin regarding the request (e.g., rejection reason)', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='AudioXApp.creator')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'db_table': 'WITHDRAWAL_REQUESTS',
                'ordering': ['-request_date'],
            },
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_duration',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='chapter_time',
        ),
    ]
