# Generated by Django 4.2.19 on 2025-05-28 06:42

import AudioXApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0003_alter_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional cover image for the room.', null=True, upload_to=AudioXApp.models.chatroom_cover_image_path),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('UR', 'Urdu'), ('PA', 'Punjabi'), ('SI', 'Sindhi')], default='EN', help_text='Primary language of the chat room.', max_length=2),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='description',
            field=models.TextField(default='No description provided.', help_text='Description for the chat room.'),
            preserve_default=False,
        ),
    ]
