# Generated by Django 4.2.19 on 2025-05-25 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0003_listeninghistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='AudioXApp.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Library Item',
                'verbose_name_plural': 'User Library Items',
                'db_table': 'USER_LIBRARY_ITEMS',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'audiobook')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='library_audiobooks',
            field=models.ManyToManyField(blank=True, related_name='saved_in_libraries', through='AudioXApp.UserLibraryItem', to='AudioXApp.audiobook'),
        ),
    ]
