# Generated by Django 5.1.5 on 2025-02-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0003_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('roles', models.CharField(blank=True, choices=[('full_access', 'Full Access'), ('manage_content', 'Manage Content'), ('manage_creators', 'Manage Creators'), ('manage_discussions', 'Manage Discussions'), ('manage_transactions', 'Manage Transactions')], max_length=255)),
            ],
            options={
                'db_table': 'ADMINS',
            },
        ),
    ]
