# Generated by Django 4.2.19 on 2025-05-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0004_chatroom_cover_image_chatroom_language_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroominvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroominvitation',
            name='invited_user',
            field=models.ForeignKey(default=1, help_text='User who is invited to the room.', on_delete=django.db.models.deletion.CASCADE, related_name='received_chat_invitations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroominvitation',
            name='invited_by',
            field=models.ForeignKey(help_text='User who sent the invitation.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatroominvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='chatroominvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('room', 'invited_user'), name='unique_pending_invitation_per_user_per_room'),
        ),
        migrations.RemoveField(
            model_name='chatroominvitation',
            name='invited_email',
        ),
    ]
