# Generated by Django 4.2.19 on 2025-04-29 17:16

import AudioXApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0004_alter_audiobook_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='application_attempts_current_month',
            field=models.PositiveIntegerField(default=0, help_text='Number of applications submitted in the current cycle (resets monthly)'),
        ),
        migrations.AddField(
            model_name='creator',
            name='last_application_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent application submission', null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='rejection_popup_shown',
            field=models.BooleanField(default=False, help_text="Has the 'Application Rejected' popup been shown?"),
        ),
        migrations.AddField(
            model_name='creator',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin if application is rejected', null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='welcome_popup_shown',
            field=models.BooleanField(default=False, help_text="Has the 'Welcome Creator' popup been shown?"),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cnic_back',
            field=models.ImageField(help_text='Back side of CNIC', null=True, upload_to=AudioXApp.models.creator_cnic_path),
        ),
        migrations.AlterField(
            model_name='creator',
            name='cnic_front',
            field=models.ImageField(help_text='Front side of CNIC', null=True, upload_to=AudioXApp.models.creator_cnic_path),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_name',
            field=models.CharField(help_text='Public display name for the creator', max_length=100),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_unique_name',
            field=models.CharField(help_text='Unique handle (@yourname) for URLs and mentions', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_creator_unique_name', message='Unique name can only contain letters, numbers, and underscores.', regex='^[a-zA-Z0-9_]+$')]),
        ),
        migrations.AlterField(
            model_name='creator',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when creator terms were accepted', null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('monthly', 'Monthly Premium'), ('annual', 'Annual Premium')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('pending', 'Pending Payment'), ('failed', 'Payment Failed')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes from admin (e.g., rejection reason, processing details)', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='processed_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was processed/completed/failed', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='pending', max_length=15),
        ),
    ]
