# Generated by Django 5.1.5 on 2025-02-13 10:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0005_user_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coins', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('purchase_time', models.TimeField(default=datetime.time(15, 19, 6, 187831))),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Failed', 'Failed')], max_length=20)),
                ('coin_pack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AudioXApp.coinpack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
