# Generated by Django 4.2.19 on 2025-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0005_alter_chatroominvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroommember',
            name='left_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user left or was removed from the room.', null=True),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('left', 'Left Voluntarily'), ('room_dismissed', 'Room Dismissed')], db_index=True, default='active', help_text='Current status of the member in the room.', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('audiobook_recommendation', 'Audiobook Recommendation'), ('user_joined', 'User Joined Notification'), ('user_left', 'User Left Notification'), ('room_created', 'Room Created Notification'), ('room_renamed', 'Room Renamed Notification')], default='text', max_length=30),
        ),
    ]
