# Generated by Django 4.2.18 on 2025-02-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0005_user_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('creator_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_audiobooks', models.PositiveIntegerField(default=0)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'CREATORS',
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('audiobook_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('narrator', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('file_url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobooks', to='AudioXApp.creator')),
            ],
            options={
                'db_table': 'AUDIOBOOKS',
            },
        ),
    ]
