# Generated by Django 4.2.19 on 2025-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0005_creator_application_attempts_current_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='cid',
            field=models.CharField(blank=True, db_index=True, help_text='Unique Creator ID (e.g., cid-1001), generated upon approval.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
