# Generated by Django 4.2.18 on 2025-02-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0006_creator_audiobook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=255)),
                ('chapter_order', models.PositiveIntegerField()),
                ('chapter_time', models.PositiveIntegerField(help_text='Start time in seconds')),
                ('chapter_duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='chapters/')),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='AudioXApp.audiobook')),
            ],
            options={
                'db_table': 'CHAPTERS',
                'ordering': ['chapter_order'],
            },
        ),
    ]
