# Generated by Django 5.1.5 on 2025-02-13 10:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0006_coinpack_coinpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpurchase',
            name='coin_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AudioXApp.coinpack'),
        ),
        migrations.AlterField(
            model_name='coinpurchase',
            name='purchase_time',
            field=models.TimeField(default=datetime.time(15, 50, 50, 584814)),
        ),
        migrations.AlterField(
            model_name='coinpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
