# Generated by Django 4.2.19 on 2025-04-30 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0006_creator_cid_alter_user_is_superuser_and_more'),
    ]

    operations = [
    ]
