# Generated by Django 4.2.19 on 2025-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0006_chatroommember_left_at_chatroommember_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_at', 'status'], 'verbose_name': 'Chat Room', 'verbose_name_plural': 'Chat Rooms'},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed by Owner')], db_index=True, default='active', help_text='The current status of the chat room (Active, Closed, etc.)', max_length=15),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(help_text='Content of the message. For recommendations, this might be an optional comment or the system message text.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('audiobook_recommendation', 'Audiobook Recommendation'), ('user_joined', 'User Joined Notification'), ('user_left', 'User Left Notification'), ('room_created', 'Room Created Notification'), ('room_renamed', 'Room Renamed Notification'), ('room_closed', 'Room Closed Notification')], default='text', max_length=30),
        ),
    ]
