# Generated by Django 4.2.19 on 2025-05-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0002_userdownloadedaudiobook'),
        ('AudioXApp', '0007_alter_chatroom_options_chatroom_status_and_more'),
    ]

    operations = [
    ]
