# Generated by Django 4.2.19 on 2025-04-30 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0007_alter_user_id_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='available_balance',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='total_audiobooks',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='total_earning',
        ),
        migrations.AddField(
            model_name='creator',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the application was approved.', null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_creators', to='AudioXApp.admin'),
        ),
        migrations.AddField(
            model_name='creator',
            name='attempts_at_approval',
            field=models.PositiveIntegerField(blank=True, help_text='Number of attempts made when this application was approved.', null=True),
        ),
    ]
