# Generated by Django 4.2.19 on 2025-04-30 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0008_remove_creator_available_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='creator',
            name='total_audiobooks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='creator',
            name='total_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last updated the status (approved, rejected, completed, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to='AudioXApp.admin'),
        ),
    ]
