# Generated by Django 4.2.19 on 2025-04-30 09:23

import AudioXApp.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0009_creator_available_balance_creator_total_audiobooks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorApplicationLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when this specific application was submitted')),
                ('attempt_number_monthly', models.PositiveIntegerField(help_text='Which attempt this was in the submission month')),
                ('creator_name_submitted', models.CharField(max_length=100)),
                ('creator_unique_name_submitted', models.CharField(max_length=50)),
                ('cnic_front_submitted', models.ImageField(blank=True, help_text='CNIC Front submitted for this attempt', null=True, upload_to=AudioXApp.models.creator_cnic_path)),
                ('cnic_back_submitted', models.ImageField(blank=True, help_text='CNIC Back submitted for this attempt', null=True, upload_to=AudioXApp.models.creator_cnic_path)),
                ('terms_accepted_at_submission', models.DateTimeField(help_text='Timestamp when terms were accepted for this submission')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, help_text='Timestamp when the application was approved or rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason provided if this specific application was rejected', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_logs', to='AudioXApp.creator')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who approved or rejected this specific application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_creator_applications', to='AudioXApp.admin')),
            ],
            options={
                'verbose_name': 'Creator Application Log',
                'verbose_name_plural': 'Creator Application Logs',
                'db_table': 'CREATOR_APPLICATION_LOGS',
                'ordering': ['creator', '-application_date'],
            },
        ),
    ]
