# Generated by Django 4.2.19 on 2025-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0009_chapter_external_audio_url_alter_chapter_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='duration',
            field=models.DurationField(blank=True, help_text="Duration of this chapter's audio.", null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, help_text='Size of the audio file in bytes.', null=True),
        ),
    ]
