# Generated by Django 4.2.19 on 2025-04-30 11:39

import AudioXApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0010_creatorapplicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='creator_profile_pic',
            field=models.ImageField(blank=True, help_text='Optional: Specific profile picture for the creator page.', null=True, upload_to=AudioXApp.models.creator_profile_pic_path),
        ),
        migrations.AddField(
            model_name='creator',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False, help_text='Is this creator currently banned?'),
        ),
    ]
