# Generated by Django 5.1.5 on 2025-02-13 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0010_alter_admin_table_alter_cointransaction_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('reward', 'Reward'), ('spent', 'Spent'), ('refund', 'Refund'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received')], max_length=15),
        ),
    ]
