# Generated by Django 4.2.19 on 2025-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0010_chapter_duration_chapter_size_bytes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='duration',
        ),
        migrations.AddField(
            model_name='chapter',
            name='duration_seconds',
            field=models.FloatField(blank=True, help_text='Duration of the chapter in seconds.', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file for the chapter.', null=True, upload_to='chapters_audio/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='external_audio_url',
            field=models.URLField(blank=True, help_text='URL for externally hosted audio (e.g., LibriVox, Archive.org). audio_file will be ignored if this is set.', max_length=1024, null=True),
        ),
    ]
