# Generated by Django 4.2.19 on 2025-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0011_creator_creator_profile_pic_creator_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='ban_reason',
            field=models.TextField(blank=True, help_text='Reason provided by admin if creator is banned.', null=True),
        ),
    ]
