# Generated by Django 4.2.19 on 2025-06-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0011_remove_chapter_duration_chapter_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requires_extra_details_post_social_signup',
            field=models.BooleanField(default=False, help_text='True if user signed up via social media and needs to provide additional details like phone/bio.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
