# Generated by Django 4.2.19 on 2025-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0012_user_requires_extra_details_post_social_signup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='requires_extra_details_post_social_signup',
            field=models.BooleanField(default=False, help_text='True if user signed up via social media and needs to provide phone number and confirm/edit full name.'),
        ),
    ]
