# Generated by Django 4.2.19 on 2025-04-30 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0012_creator_ban_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admins (e.g., unban reason).', null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='banned_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the creator was banned.', null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='banned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who banned this creator.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_creators', to='AudioXApp.admin'),
        ),
    ]
