# Generated by Django 4.2.19 on 2025-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0013_alter_user_requires_extra_details_post_social_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='source_document_filename',
            field=models.CharField(blank=True, help_text='Original filename of the document used for TTS generation, if applicable.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='tts_voice_id',
            field=models.CharField(blank=True, help_text='Voice used if audio was generated by TTS.', max_length=100, null=True),
        ),
    ]
