# Generated by Django 5.1.5 on 2025-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0013_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
