# Generated by Django 4.2.19 on 2025-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0013_creator_admin_notes_creator_banned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='last_name_change_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last display name change.', null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='last_unique_name_change_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last unique name (@handle) change.', null=True),
        ),
    ]
