# Generated by Django 4.2.19 on 2025-05-02 10:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0014_creator_last_name_change_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('bank', 'Bank Account'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa')], max_length=20)),
                ('account_title', models.CharField(help_text='Full name registered with the account.', max_length=100)),
                ('account_identifier', models.CharField(help_text='Account Number (JazzCash/Easypaisa) or IBAN (Bank Account).', max_length=34)),
                ('bank_name', models.CharField(blank=True, help_text="Required only if Account Type is 'Bank Account'.", max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark one account as primary for withdrawals.')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Timestamp when this account was last used for a withdrawal.', null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_accounts', to='AudioXApp.creator')),
            ],
            options={
                'db_table': 'WITHDRAWAL_ACCOUNTS',
                'ordering': ['creator', '-added_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='withdrawalaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('creator',), name='unique_primary_withdrawal_account'),
        ),
    ]
