# Generated by Django 4.2.19 on 2025-05-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0015_withdrawalaccount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='withdrawal_account',
            field=models.ForeignKey(help_text='The account selected for this withdrawal request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='AudioXApp.withdrawalaccount'),
        ),
    ]
