# Generated by Django 4.2.19 on 2025-05-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0016_withdrawalrequest_withdrawal_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='account_identifier',
            field=models.CharField(help_text='Account Number (JazzCash/Easypaisa/Nayapay/Upaisa) or IBAN (Bank Account).', max_length=34),
        ),
        migrations.AlterField(
            model_name='withdrawalaccount',
            name='account_type',
            field=models.CharField(choices=[('bank', 'Bank Account'), ('jazzcash', 'JazzCash'), ('easypaisa', 'Easypaisa'), ('nayapay', 'Nayapay'), ('upaisa', 'Upaisa')], max_length=20),
        ),
    ]
