# Generated by Django 4.2.19 on 2025-05-02 18:20

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0017_alter_withdrawalaccount_account_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='file_url',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Is this audiobook paid or free?'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in PKR if the audiobook is paid (set to 0.00 if free).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='audiobook_covers/'),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio_file',
            field=models.FileField(null=True, upload_to='chapters/'),
        ),
    ]
