# Generated by Django 4.2.19 on 2025-05-04 11:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0018_remove_audiobook_file_url_audiobook_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='total_views',
            field=models.PositiveIntegerField(default=0, help_text='Total number of times the audiobook detail page has been viewed.'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text="User's review comment (optional).", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='AudioXApp.audiobook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audiobook Review',
                'verbose_name_plural': 'Audiobook Reviews',
                'db_table': 'REVIEWS',
                'ordering': ['-created_at'],
                'unique_together': {('audiobook', 'user')},
            },
        ),
    ]
