# Generated by Django 4.2.19 on 2025-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0019_audiobook_total_views_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_payment_method_brand',
            field=models.CharField(blank=True, help_text='e.g., visa, mastercard', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_payment_method_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits of the card', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('pending', 'Pending Payment'), ('failed', 'Payment Failed'), ('past_due', 'Past Due')], db_index=True, default='active', max_length=10),
        ),
    ]
