# Generated by Django 4.2.19 on 2025-05-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0021_audiobookpurchase_remove_creator_total_audiobooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='last_withdrawal_request_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last withdrawal request made by the creator.', null=True),
        ),
        migrations.AddField(
            model_name='creatorearning',
            name='audiobook_title_at_purchase',
            field=models.CharField(blank=True, help_text='Title of the audiobook at the time of purchase.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='processed_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was processed/completed/failed/rejected', null=True),
        ),
    ]
