# Generated by Django 4.2.19 on 2025-05-09 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0022_creator_last_withdrawal_request_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorearning',
            name='audiobook_title_at_purchase',
        ),
        migrations.AddField(
            model_name='creatorearning',
            name='audiobook_title_at_transaction',
            field=models.CharField(blank=True, help_text='Title of the audiobook at the time of the transaction.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creatorearning',
            name='earning_per_view_at_transaction',
            field=models.DecimalField(blank=True, decimal_places=4, help_text="Earning rate per view at the time of this transaction, if type is 'view'.", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='creatorearning',
            name='earning_type',
            field=models.CharField(choices=[('sale', 'Sale Earning'), ('view', 'View Earning')], db_index=True, default='sale', max_length=10),
        ),
        migrations.AddField(
            model_name='creatorearning',
            name='view_count_for_earning',
            field=models.PositiveIntegerField(blank=True, help_text="Number of views this earning entry represents, if type is 'view'.", null=True),
        ),
        migrations.AlterField(
            model_name='creatorearning',
            name='amount_earned',
            field=models.DecimalField(decimal_places=2, help_text='Net amount earned by the creator for this transaction (sale or view batch).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='creatorearning',
            name='audiobook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earning_entries', to='AudioXApp.audiobook'),
        ),
        migrations.AlterField(
            model_name='creatorearning',
            name='notes',
            field=models.TextField(blank=True, help_text="Any notes related to this earning (e.g., 'From audiobook sale', 'Monthly view payout').", null=True),
        ),
        migrations.AlterField(
            model_name='creatorearning',
            name='purchase',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='earning_record', to='AudioXApp.audiobookpurchase'),
        ),
        migrations.AlterField(
            model_name='creatorearning',
            name='transaction_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='AudiobookViewLog',
            fields=[
                ('view_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('audiobook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='AudioXApp.audiobook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiobook_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audiobook View Log',
                'verbose_name_plural': 'Audiobook View Logs',
                'db_table': 'AUDIOBOOK_VIEW_LOGS',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['audiobook', 'viewed_at'], name='AUDIOBOOK_V_audiobo_0ca16b_idx'), models.Index(fields=['user', 'audiobook', 'viewed_at'], name='AUDIOBOOK_V_user_id_182167_idx')],
            },
        ),
    ]
