# Generated by Django 4.2.19 on 2025-05-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0023_remove_creatorearning_audiobook_title_at_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('PUBLISHED', 'Published'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected'), ('PAUSED_BY_ADMIN', 'Paused by Admin'), ('UNPUBLISHED', 'Unpublished by Creator')], db_index=True, default='PENDING', help_text='The current status of the audiobook.', max_length=20),
        ),
    ]
