# Generated by Django 4.2.19 on 2025-05-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0024_audiobook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published'), ('INACTIVE', 'Inactive'), ('REJECTED', 'Rejected'), ('PAUSED_BY_ADMIN', 'Paused by Admin')], db_index=True, default='PUBLISHED', help_text='The current status of the audiobook.', max_length=20),
        ),
    ]
