# Generated by Django 4.2.19 on 2025-05-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0025_alter_audiobook_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='last_withdrawal_request_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last non-cancelled withdrawal request made by the creator.', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='processed_date',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was processed/completed/failed/rejected/cancelled', null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected by Admin'), ('failed', 'Failed'), ('cancelled', 'Cancelled by Creator')], db_index=True, default='pending', max_length=25),
        ),
    ]
