# Generated by Django 4.2.19 on 2025-05-11 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0026_alter_creator_last_withdrawal_request_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiobook',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='audiobook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the audiobook record was created.'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the audiobook record was last updated.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the chapter was added.'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the chapter was last updated.'),
        ),
        migrations.AddField(
            model_name='creator',
            name='profile_pic_updated_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last profile picture update.', null=True),
        ),
    ]
