# Generated by Django 4.2.19 on 2025-05-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0027_alter_audiobook_options_audiobook_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobookpurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='chapter',
            name='text_content',
            field=models.TextField(blank=True, help_text='Transcribed text of the audio chapter. Generated automatically if empty.', null=True),
        ),
    ]
