# Generated by Django 4.2.19 on 2025-05-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0028_audiobookpurchase_status_chapter_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobookpurchase',
            name='audiobook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiobook_sales', to='AudioXApp.audiobook'),
        ),
    ]
