# Generated by Django 4.2.19 on 2025-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0029_alter_audiobookpurchase_audiobook'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_tts_generated',
            field=models.BooleanField(default=False, help_text="True if this chapter's audio was generated using Text-to-Speech."),
        ),
        migrations.AddField(
            model_name='chapter',
            name='tts_voice_id',
            field=models.CharField(blank=True, choices=[('default', 'Original Uploaded Audio'), ('ali_narrator', 'Ali Narrator (Male PK)'), ('aisha_narrator', 'Aisha Narrator (Female PK)')], default='default', help_text='Voice used if audio was generated by TTS.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file for the chapter (MP3, WAV, OGG). Either upload this or provide text for TTS.', null=True, upload_to='chapters_audio/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='text_content',
            field=models.TextField(blank=True, help_text='Text content for this chapter. Used for TTS if audio_file is not uploaded directly, or can be generated from uploaded audio via STT.', null=True),
        ),
    ]
