# Generated by Django 4.2.19 on 2025-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudioXApp', '0030_chapter_is_tts_generated_chapter_tts_voice_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='tts_voice_id',
            field=models.CharField(blank=True, choices=[('ali_narrator', 'Ali Narrator (Male PK)'), ('aisha_narrator', 'Aisha Narrator (Female PK)')], default=None, help_text='Voice used if audio was generated by TTS.', max_length=50, null=True),
        ),
    ]
